### ISSUE TITLE
Results not visible using https due to mixed content

### ISSUE THREAD

**Issue by krehl** [bpmn-miwg/bpmn-miwg-tools#20] opened 2015-11-18 18:24 UTC
For everybody accessing the page via HTTPS the results will not display due to mixed content. Since a lot of people nowadays use HTTPS Everywhere or similar extensions, i propose to change the links to use https as well and - for simplicity - to only serve the page via https, should this be possible using github.io.

Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.datatables.net/1.10.4/css/jquery.dataTables_themeroller.css'. This request has been blocked; the content must be served over HTTPS.
bpmn-miwg.github.io/:13 Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure stylesheet 'http://datatables.net/media/css/jui_themes/redmond/jquery-ui-1.7.2.custom.css'. This request has been blocked; the content must be served over HTTPS.
bpmn-miwg.github.io/:1 Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure script 'http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js'. This request has been blocked; the content must be served over HTTPS.
bpmn-miwg.github.io/:1 Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure script 'http://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js'. This request has been blocked; the content must be served over HTTPS.
bpmn-miwg.github.io/:22 Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure stylesheet 'http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css'. This request has been blocked; the content must be served over HTTPS.
bpmn-miwg.github.io/:1 Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure script 'http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js'. This request has been blocked; the content must be served over HTTPS.
bpmn-miwg.github.io/:31 Uncaught ReferenceError: $ is not defined

![image](https://cloud.githubusercontent.com/assets/1944048/11249732/ffd7fa08-8e28-11e5-9546-ccd6e2bdab50.png)

**Comment by tstephen** [comment] 2022-10-06 16:31
Duplicate of #25

**Closed by tstephen** 2022-10-06 16:31 UTC
