### ISSUE TITLE
Properly render tools page via HTTPS

### ISSUE THREAD

**Issue by nikku** [bpmn-miwg/bpmn-miwg-tools#25] opened 2016-01-15 07:23 UTC
People using HTTPS to access https://bpmn-miwg.github.io/bpmn-miwg-tools/ cannot see the site contents because external resources are not properly linked to via HTTPS:

```
Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.datatables.net/1.10.4/css/jquery.dataTables_themeroller.css'. This request has been blocked; the content must be served over HTTPS.
(index):13 Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure stylesheet 'http://datatables.net/media/css/jui_themes/redmond/jquery-ui-1.7.2.custom.css'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure script 'http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure script 'http://cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js'. This request has been blocked; the content must be served over HTTPS.
(index):22 Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure stylesheet 'http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://bpmn-miwg.github.io/bpmn-miwg-tools/' was loaded over HTTPS, but requested an insecure script 'http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js'. This request has been blocked; the content must be served over HTTPS.
```

The solution is to always embed resources via HTTPS (recommended by web guys) or use the `//` prefix for links to either choose HTTP or HTTPS based on the protocol the website was opened itself.

Need to verify that all external resources are actually available via HTTPS before though.

**Comment by barmac** [comment] 2022-05-13 09:06
I cannot reproduce this anymore. Shall we close the issue?

**Comment by barmac** [comment] 2022-05-13 09:17
BTW this is a duplicate of https://github.com/bpmn-miwg/bpmn-miwg-tools/issues/20

**Closed** 2022-10-06 16:29 UTC
